language: python
python:
  - "3.5"
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE test_user WITH PASSWORD 'test_password';" -U postgres
  - psql -c "ALTER ROLE test_user WITH LOGIN SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE adkintun_test WITH OWNER test_user;" -U postgres
script: python manage.py test
