language: python
python:
  - "3.5"
services:
  - postgresql
before_script:
  - psql -c "CREATE ROLE user_test WITH PASSWORD 'password_test';" -U postgres
  - psql -c "ALTER ROLE user_test WITH LOGIN SUPERUSER;" -U postgres
  - psql -c "CREATE DATABASE adkintun_test WITH OWNER user_test;" -U postgres
script: python manage.py test
