"""empty message

Revision ID: afa2461a6ac9
Revises: None
Create Date: 2016-01-25 14:38:08.301981

"""

# revision identifiers, used by Alembic.
revision = 'afa2461a6ac9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antennas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('lac', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('mcc', sa.Integer(), nullable=True),
    sa.Column('mnc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('board', sa.String(length=50), nullable=True),
    sa.Column('build_id', sa.String(length=50), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('hardware', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('release', sa.String(length=50), nullable=True),
    sa.Column('release_type', sa.String(length=50), nullable=True),
    sa.Column('product', sa.String(length=50), nullable=True),
    sa.Column('sdk', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('sims',
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('serial_number')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sims')
    op.drop_table('devices')
    op.drop_table('carriers')
    op.drop_table('antennas')
    ### end Alembic commands ###
