from tests.events.save_application_event_test import SaveApplicationEventTestCase
from tests.events.save_connectivity_event_test import SaveConnectivityEventTestCase
from tests.events.save_events_with_device_and_sim_test import SaveEventsWithDeviceAndSimTestCase
from tests.events.save_gsm_observation_event_test import SaveGsmObservationEventTestCase
from tests.events.save_mobile_event_test import SaveMobileEventTestCase
from tests.events.save_new_telco_events import SaveNewTelcoEventsTestCase
from tests.events.save_wifi_event_test import SaveWifiEventTestCase
from tests.events.save_multiple_events_with_device_and_sim_test import SaveMultipleEventsWithDeviceAndSimTestCase
